name: nightly-build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Daily “At 00:00”

jobs:
  build:
    uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
    with:
      environment_name: atm320

  link-check:
    uses: ProjectPythia/cookbook-actions/.github/workflows/link-checker.yaml@main
